### ISSUE TITLE
Insp is a focking joke

### ISSUE THREAD

**Issue by ibanez0r** [inspircd/inspircd#1007]
We deployed insp to our chat network, 3.1mb of resources gobbled up, decided to swap it out for unrealircd, 33kb of resources being used, you guys should do the world a favor and fucking rm -rf your development tree you idiots!

**Comment by Agent-Isai** [comment]
Please refrain from swearing, inspircd might use that many resources as you might have many users or you have loaded many modules that use a lot of resources.

**Comment by ibanez0r** [comment]
Its the same amount of users that unrealircd is now using, only 1/10th of the resources! the ircd you are developing is broken.

**Comment by Agent-Isai** [comment]
Well, some modules on Inspircd do take quite some resources like m_clones.so. That's why I suggest check the description or something before loading them

**Comment by md-5** [comment]
This is a day and age where pretty much every computer has 8,000,000mb of ram, and even the cheapest little $3/year hosts give you 128mb of ram, and you are complaining about 3.1mb.

**Comment by SaberUK** [comment]
@md-5 Please don't feed the troll.

**Comment by rburchell** [comment]
Thanks for the suggestion.

As this isn't a terribly constructive issue as-is, I'll close this, but I will provide some advise for memory measurement if you want to investigate further.

First things first, you want to determine if memory use is actually a problem or not. Using a tool like 'top' is not a good measurement, because it doesn't provide the full picture: RSS and VSS are both more or less useless when it comes to determining actual usage. You want to look at the USS, primarily, because that's the amount that isn't shared between any other processes on the system. To make this clearer: applications can share resources by using shared libraries. But because they are _shared_, they are only "used" once. For more of an explanation behind this, see[0].

Another useful way to measure is to use `free`. If you run it before you start a process, and again after (if you try as much as you can to ensure that nothing changes between), and look at the "used" field under -/+ buffers/cache (and Swap, if you have a heavily loaded system), you'll get an idea of how much is used (don't look at the "Mem:" line, because disk cache/etc is counted here, so the numbers you get will be close to useless).

Once you find out that memory usage is in fact a problem, then you need to look into what specifically is causing this problem. For that, you need a heap profiler.

* Instruments on OS X has a great memory profiler tool[1]
* Valgrind has a pretty decent memory profiler tool (without the benefit of a UI, unfortunately) in the form of massif[2]
* Linux also has the heaptrack tool[3]

The idea behind these is you run the application to trace under the tool, perform your usecase, and then examine the diagnostics to figure out what's going on "under the hood". You'll generally get a list of stacktraces along with how much memory was allocated by each stack.

After analysis, you can open issues with your findings for someone to take a look at. If you want to do more than analyze, you can then even try *reduce* the memory allocated by each stack, if you're feeling awesome, and submit patches. Some common tricks to do this:
* Make structs smaller by removing unused members
* Correctly ordering structs correctly to remove holes[4]
* Reduce the size of allocations if they are unnecessarily large (e.g. if you have a buffer to process an IRC line, and it's 10mb in size, it's way too large given the average size of most IRC lines -- assuming you can stick with the RFC, then the maximum size you should encounter would be under 1kb, significantly smaller)
* Make sure allocations are freed (if in the above analysis you ever see constantly growing allocations from a stack without e.g. a corresponding growing number of users, you may be looking at some kind of memory leak which needs fixing)
* Use bitfields (and if C++11 is allowed, enum classes) to restrict data fields to the smallest possible size for the values required

There are also some other more esoteric tricks out there, like:
* Removing infrequently used members out of a struct into an "ExtraData" type struct (not usually allocated, only allocated when a member of that struct is required)
* Similarly, one could move really infrequently used members out of structs altogether, and into some form of global hashtable for such data, at a serious penalty of performance in accessing such data
* Using tagged pointers[5] to store data
* Look into dealing with memory fragmentation by using block/pool allocation for specific types, allocate long-lived types as early as possible, etc.

As I hope I've been able to communicate, there's quite a lot of work involved in this sort of thing, and it does require some degree of knowledge (and patience) to undertake. It's not impossible, and I'd certainly welcome some help seeing it done. I can say that for myself (and likely a lot of others), though, that this sort of work is not a priority due to the typical environments InspIRCd is run in (being quite rich in resources, and the amounts in question not being all that huge).

[0]: https://stackoverflow.com/questions/22372960/is-this-explanation-about-vss-rss-pss-uss-accurately
[1]: https://developer.apple.com/library/mac/documentation//AnalysisTools/Reference/Instruments_User_Reference/AllocationsInstrument/AllocationsInstrument.html
[2]: http://valgrind.org/docs/manual/ms-manual.html
[3]: http://milianw.de/blog/heaptrack-a-heap-memory-profiler-for-linux
[4]: http://www.catb.org/esr/structure-packing/
[5]: https://en.wikipedia.org/wiki/Tagged_pointer
