### ISSUE TITLE
Problem with gnutls

### ISSUE THREAD

**Issue by shibumi** [inspircd/inspircd#1042]
Hello,
How can I fix this issue?
```
[*] Unable to initialize m_ssl_gnutls.so: Unable to load GnuTLS server certificate (/home/irc/inspircd-2.0.19/run/conf/cert.pem): The peer did not send any certificate.
```

cert.pem and key.pem exist both in this folder..

my gnutls config in modules.conf

```
<gnutls certfile="/home/irc/inspircd-2.0.19/run/conf/cert.pem" keyfile="/home/irc/inspircd-2.0.19/run/conf/key.pem" priority="NORMAL:-MD5" hash="sha1">
```

**Comment by SaberUK** [comment]
Where did you obtain your cert from?

P.S. If you are using the default location for `<gnutls:certfile>` (which it looks like you are) then you don't need to specify it in the config.

**Comment by shibumi** [comment]
I generated the cert by my self with the certtool template... its selfsigned

**Comment by SaberUK** [comment]
Which certtool template did you use? Can you share it?

The recommended way to generate a self signed cert is using `./configure --generate-gnutls-cert` though.

**Comment by shibumi** [comment]
I did it via normal ./configure... when I chose gnutls instead of openssl and this generated a template for me. Then I generated the cert.pem and key.pem files with:

```
certtool --generate-privkey --outfile key.pem
certtool --generate-privkey --load-privkey key.pem --outfile cert.pem
```

so what did I wrong?

**Comment by attilamolnar** [comment]
@shibumi There is a lot of things that can be wrong, please provide a full directory tree (with permissions). Also note that this is an issue tracker and is not mainly for support, next time please use our IRC support channel to get faster answers.

**Comment by qnxor** [comment]
Sorry to revive this, but since this thread is the first Google hit when searchinig for this problem, I wanted to add a potential solution. In my case it was file permissions. I use the Ubuntu package and inspircd runs as the user "irc", which did not have read access to the certificate or private key file.

The error message was the same, which I htink the developers could actually improve to say "permission denied to user irc while reading <file>.pem" ... would have saved me quite some time.
