### ISSUE TITLE
Wildcard characters in channel names may cause trouble

### ISSUE THREAD

**Issue by webczat** [inspircd/inspircd#1045]
Inspircd, as per rfc, allows most possible characters in channel names unless denied by a module.
However I believe that wildcard characters * and ? should also be denied. The reason is that such channels break wildcard matching in modules like m_channelban.
You are not able to, for example, use m_channelban on a channel called #* or similar, because if you do so, you ban all channels. I am avare of the fact that I can actually do it using m_deniednames.

**Comment by SaberUK** [comment]
We should fix this by introducing a backslash escape character in MatchInternal.

e.g.

- `*@example.com` matches the u@h `example@example.com`
- `\*@example.com` does not match the u@h `example@example.com`
- `\*@example.com` matches the u@h `*@example.com`

**Comment by attilamolnar** [comment]
@webczat Hello,

I don't think it's a good idea to put restrictions in the core because of some module, channelban in this case. As you pointed out correctly the channames module can be used to restrict any chars in channel names, wildcards included. I think however that this is worth mentioning in the doc.
