### ISSUE TITLE
Exemptchanops should validate mode parameter syntax/permissions better

### ISSUE THREAD

**Issue by webczat** [inspircd/inspircd#1055]
Hello.

I believe that the +X channel mode (m_exemptchanops) is quite problematic, but I am not sure about the possible directions of fixes, if any.
First, the thing is that when someone sets +X with a parameter, the parameter syntax is not checked at all even though I believe it should be, as syntax is modename:prefixchar or similar.
In addition, there are no permission checks. Like any halfop may set the mode, and unset it. it allows this halfop to enable any exemption he wishes to enable, and for any prefix, liike a halfop can make voices flood protected, and override channel owner decisions if he decided that only owners are protected. It cannot be set in stone/mlocked, because if multiple +X are set for the same exemption, then the last one wins, not the first, so anyone with +h or above can override a mlock.

**Comment by GLolol** [comment]
:+1: just realized this too.

**Comment by SaberUK** [comment]
>First, the thing is that when someone sets +X with a parameter, the parameter syntax is not checked at all even though I believe it should be, as syntax is modename:prefixchar or similar.

The parameter syntax doesn't need to be checked does it? On line 200 it calls into `ModeParser::Process` which should handle syntax checking (mode.cpp line 473).

>In addition, there are no permission checks. Like any halfop may set the mode, and unset it.

This should also be handled by the mode parser in `ModeParser::TryMode` (mode.cpp lines 280-306).

**Comment by webczat** [comment]
Well, the parameter syntax is not checked this way.

W dniu 2015-06-16 o 02:50, Peter Powell pisze:

**Comment by SaberUK** [comment]
>Well, the parameter syntax is not checked this way.

Yeah, my mistake. I was looking at the wrong module (I confused +X and +Z). However,

>>First, the thing is that when someone sets +X with a parameter, the parameter syntax is not checked at all even though I believe it should be, as syntax is modename:prefixchar or similar

This is indeed an omission but it is not a serious one. As far as I can tell this isn't capable of causing a crash or a security risk for channels.

>>In addition, there are no permission checks. Like any halfop may set the mode, and unset it. 

This isn't really that dangerous considering you shouldn't be giving privileges to people you don't trust anyway. We should probably make it so people can't remove exemptions that they wouldn't pass though.

**Comment by attilamolnar** [comment]
Are you sure you cannot lock +X using m_mlock?

**Comment by GLolol** [comment]
Services won't let me set an mlock on +X since its a list mode, and I don't see any other public interface for mlock. 

`/helpop mlock` returns:

```
14:25 -- *** HELPOP for mlock
14:25 --  -
14:25 -- There is no help for the topic
14:25 -- you searched for. Please try again.
14:25 --  -
14:25 -- *** End of HELPOP
```

**Comment by SaberUK** [comment]
@attilamolnar @GLolol I think that locking list modes is something that only Anope can do.

**Comment by webczat** [comment]
I do not quite remember how it worked, but I believe you couldn't say +X
is unsettable/unremovable, only that those items of a list mode are
locked, but you can add others.
And here it is that elements added later have precedence

**Comment by webczat** [comment]
as for security risks for channels, you should not give permissions to people you don't trust, but levels like halfop/op/protect are there for a reason, if I as an owner want owners exempt from everything I can think of, I do not want halfop to remove such a thing, or to override it.

**Comment by bonnedav** [comment]
Just wondering if anyone is still working on this.

**Comment by TurkDesk** [comment]
@GLolol @SaberUK Atheme has mlock, you would need try /cs help set mlock , not /helpop mlock
However if you try something for X mode, ie /cs set #mytest mlock +X blockcolor:h
You will get -ChanServ- The MLOCK for #mytest has been removed.
Basically you can not use the mode with mlock and worse u will be removing the modes u had.
In /cs set #mytest mlock +ntX blockcolor:h case you will get 
-ChanServ- The MLOCK for #mytest has been set to +nt. where X is just been ignored.

**Comment by GLolol** [comment]
@TurkDesk I am aware..

**Comment by sebastiannielsen** [comment]
You could try with this module I created. It works for listmodes, and allows you to restrict the mode usage to for example owner+admin Only (q and a).
https://github.com/inspircd/inspircd-extras/blob/master/2.0/m_moderestrict.cpp

`<moderestrict mode="X" rank="50000">` - restrict X usage (set or unset) to owner Only.
or
`<moderestrict mode="X" rank="40000">` - restrict X usage (set or unset) to owner+admin Only.

**Comment by Robby-** [comment]
> This isn't really that dangerous considering you shouldn't be giving privileges to people you don't trust anyway. We should probably make it so people can't remove exemptions that they wouldn't pass though.

I came across this issue as well and it would be good indeed to have restrictions on who can remove these, but also who can set them, to be honest. Because it doesn't make sense that for example an halfop (or even ops and admins) can exempt themselves for something they shouldn't be able to do in the first place. One can argue that you should only give trusted users halfop (or whatever else) privileges, but some measures to prevent this on the ircd-side would still be good to have regardless.

Then again, I too am not sure how feasible this is, given how halfops works.

And a solution like suggested in the comment above this one (about using the extras `m_moderestrict` module, nice module btw) will in turn not work for unregistered channels as the users in those channels are unable to get +a or +q without registering it, and so wouldn't be able to use +X at all. Sure, you can lower the rank to 30000 to accommodate for this, but then it recreates the problem for registered channels, as then regular ops will be able to change any +X exemption just as halfops previously could do prior to using this module).

**Comment by sebastiannielsen** [comment]
Robby: It isn't a big problem if certain modes are locked to registred channels only. The thing is that its impossible for the ircd itself to know if the channel is registred or not.

Since X is a listmode, you can also use m_banprotect.so https://github.com/inspircd/inspircd-extras/blob/master/2.0/m_banprotect.cpp to prevent anyone removing a listmode that a higher one set. Using moderestrict in combination with banprotect might give exactly what you want.
