### ISSUE TITLE
C++ Redistributable DLL dependency on Windows Executable

### ISSUE THREAD

**Issue by RAGNOARAKNOS** [inspircd/inspircd#1285]
After installing the current windows release (v2.0.23) on a Windows Server 2016, it is not possible to launch the application without installing the VS 2010 C++ redistributable packages manually due to a dependency on the MSVCP100.dll.  Could this dependency be checked by the installer? Could the re-distributable package be embedded with the installer?

**Comment by SaberUK** [comment]
cc: @Adam-

**Comment by Adam-** [comment]
Fixed in https://github.com/inspircd/inspircd/commit/1daaf3b84d87e543ee43c2f8b9b3cd0a02787424

Note that this also requires building with a non-express edition version of VS. The express editions do not include the redistributable files. Historically I have been building releases with VS2010 Express, so it has not been able to include them (even though they were going into the wrong folder, anyway).

I do have a non-express version of VS 2012, so I will begin building releases against that. I have verified locally that it installs the redistributables and they are included in the cpack generated installers.
