### ISSUE TITLE
3.0.0a1 - cannot create new xline db

### ISSUE THREAD

**Issue by Casey952** [inspircd/inspircd#1301]
On 3.0.0a1 with Xtheme (Atheme Fork)

When you do not identify to your nick and changes to a Guest nick - 3.0.0a1 brings up hundreds of these notices, and after you disconnect Xtheme, it still keeps doing these notices.

*** ANNOUNCEMENT: database: cannot create new xline db "/home/.../inspircd-3.0.0a1/run/data/data/xline.db.new": No such file or directory (2)

**Comment by Casey952** [comment]
It happens at the point when it changes your nick to Guest when you do not identify to your nick.

Changing to your nick from Guest on the first Guest change -- it works and changes your nick back.

The second Guest change after you change it back on the first change -- Services reserved nickname: Registered nickname.

The notices keep coming up after you get Services reserved nickname: Registered nickname.

**Comment by SISheogorath** [comment]
Can you check that `run/data/data/` exists? I guess you only have `run/data` as every good unix process InspIRCd doesn't simply create a bunch of directories just to write a file to the destination. Instead, it throws a useful error to fix the path or the wrong config.

Also, don't run alpha in production (just to mention it), as it's not supported.

This problem is based on `m_xlinedb.so` and services who uses `q-lines` or `svsnick` to prevent users from change back to the nick they were renamed from. It should also appear if you add any other `gzk-line`.

As this is a bug tracker, not a support forum, please use the [IRC Channel `#inspircd`](https://github.com/inspircd/inspircd/#links).

**Comment by SaberUK** [comment]
Alpha 1 has a typo in the config. You need to remove `data/` from the xline.db path.

**Comment by attilamolnar** [comment]
The typo @SaberUK mentions has been fixed already, @Casey952 please change your config file accordingly to resolve the problem: https://github.com/inspircd/inspircd/commit/e754d900a33d005078efde0c298ddc0bc7c6fdbb.
