### ISSUE TITLE
Hello some commands in helpop.conf not work

### ISSUE THREAD

**Issue by darksis** [inspircd/inspircd#1339]
Hello some a commands in helpop.conf and helpop-full.conf them not working like alltime and rmode
please fix them for people can use with them

**Comment by SISheogorath** [comment]
`rmode` is documented for master: https://github.com/inspircd/inspircd/blob/bf66b6dedd226b9967d876a3869b1766af38d596/docs/conf/helpop-full.conf.example#L111-L114

And as `alltime` and `rmode` are not part of the InspIRCd repository in the `insp20` branch, I don't see any need to document it. People who need it can add it themselves without a problem. I would use this rule for all modules in [extras](https://github.com/inspircd/inspircd-extras) because it creates unneeded dependencies between both repositories and right now we try to avoid that.

**Comment by genius3000** [comment]
@darksis If you're running master (for whatever reason), `alltime` and `rmode` are provided by modules which are (by default) disabled in the **config**. Enable them and they will work. Nothing to fix here.
On the other hand, if you're running insp20 (recommended for production servers), `rmode` does not exist and `alltime` is provided by a module which is (by default) disabled in the **config**.

**Comment by darksis** [comment]
no i running the new version 2.0.24 and very much a commands there not work

**Comment by genius3000** [comment]
@darksis please pastebin (gist, etc...) the error(s) you receive and your modules config.

**Comment by darksis** [comment]
@genius3000  i try to write like in explain /helpop N or some modes and this what i get
http://paste.ubuntu.com/24622579/
