### ISSUE TITLE
Migrate to C++14

### ISSUE THREAD

**Issue by SaberUK** [inspircd/inspircd#1424]
Although InspIRCd 3.0 was originally intending to support C++03 with TR1 extensions I feel that enough time has passed that users will have upgraded to a system with a C++11 capable compiler.

If this change is applied then the minimum supported compiler versions will be:

- Clang 3.3 &mdash; *2013*
- GCC 4.9 &mdash; *2014* (4.8 has some support but its standard library [has some bugs](https://stackoverflow.com/a/12665408).

Edit: I've thrown up a branch over [here](https://github.com/inspircd/inspircd/compare/master...SaberUK:master+cxx11) exorcising all of our C++03 compat stuff if anyone is interested.

**Comment by rburchell** [comment]
I'd say more than enough time, especially since 2.x is around for anyone stuck running on their toaster.

Some related reading material: https://doc.qt.io/qt-5/supported-platforms.html

**Comment by B00mX0r** [comment]
I think it's time for the move. 3.0 should be about doing what's best for InspIRCd, and the fact is, like @rburchell has said, the very tiny minority of people without C++11 support can still run the 2.x branch.

**Comment by remyabel** [comment]
I'd like to actually provide a counterpoint. LTS systems like RHEL are still stuck on GCC 4.8. This [copr build](https://copr.fedorainfracloud.org/coprs/nalika/inspircd/build/817949/) just disables the stdlib regex and uses the other modules as you mentioned, regex wasn't implemented until 4.9 for GCC. However, [C++11 support for GCC 4.8](https://gcc.gnu.org/gcc-4.8/cxx0x_status.html) is 99% complete. If you want to provide support for LTS distro users, I think switching to C++11 (not C++14) first would be better without shutting out these users from the 3.x and on branches.

**Comment by rburchell** [comment]
For RHEL/Centos specifically, the _default_ compiler may be old (because those LTS releases have an extremely long support lifecycle), but newer compilers are very easily available using scl (devtoolset-7 I think has gcc 7, but I'm not able to check at this time). Install devtoolset alongside the system compiler, and you should be fine.

Separately from this, I don't know what the plans are (I'm just sitting in the peanut gallery), but I would expect that an older major release (2.x, or 3.x) will still be supported for quite some time. This is for the "latest and greatest", it won't be retroactively applied to every prior release.

As such, I don't see why you should expect to build software released this year (or sometime in the future, given this is marked with a 4.0 milestone) on a system released several years ago. You can't expect every project to be able (or willing) to provide such a long lifecycle - the resources for it simply aren't there, backwards compatibility is often more time intensive than it looks.

**Comment by remyabel** [comment]
Well, I'm not a member so I don't know what your intentions are, but given that the codebase has polyfills for C++03 I assume that backwards compatibility was or is a goal. With that being said, the changes between C++11 and C++14 are not that significant (see [this](https://stackoverflow.com/questions/23980929/what-changes-introduced-in-c14-can-potentially-break-a-program-written-in-c1/23980931#23980931) and [this](https://gcc.gnu.org/projects/cxx-status.html)) so you would be unnecessarily pessimizing backwards compatibility unless you *really* need return type deduction instead of trailing return type.

Either way, I'm just playing devil's advocate. I'm all for modernizing codebases filled with cruft. See my PR before I made that comment as well as my other contributions.

**Comment by SaberUK** [comment]
This has been started in the new master branch.
