### ISSUE TITLE
create the numerics file for translation

### ISSUE THREAD

**Issue by cirinho** [inspircd/inspircd#1487]
the messages are inside the code of each module,
This impossible makes rapid translation .
suggestion would be to create a numeric file with all messages
to facilitate translation into other languages

**Comment by SaberUK** [comment]
I'm not really a fan of this because:

1. We are moving away from sending raw IRC messages to things like `Numeric::Numeric` which will build them at runtime using the wire format the user is using.
2. One numeric can have multiple messages in its `<trailing>` parameter so you can't have a simple numeric to message mapping.
3. Having lots of code in one header when only a bit is used in the translation unit they are included from unnecessarily slows down build times.

When IRCv3 standardise language negotiation we can hook translation into the `<trailing>` part of messages and call gettext (or whatever we choose to use) at build time to translate those messages.

**Comment by cirinho** [comment]
That´s ok,
the idea is facilitate translation into several languages, because the way it is is practically impossible, i need edit all the codes of all the modules to modify each message.

The numeric file is the format I know old, but if you do something similar to the anope project so we can use gettext

**Comment by SaberUK** [comment]
I opened #1500 as a tracking issue for translation support. Thanks for raising this though! 👍
