### ISSUE TITLE
Argon2 Support

### ISSUE THREAD

**Issue by DiamantTh** [inspircd/inspircd#1540]
Please add Support for Argon2, Argon2i and Argon2id

**Comment by SaberUK** [comment]
What benefits do these have over existing methods e.g. bcrypt or pbkdf2?

**Comment by DiamantTh** [comment]
Well Argon2 is not there as long as bcrypt, but I think you could go over to implementing this.

Not for nothing was Argon2 added in PHP7.2.
Projects like Nextcloud also use it if version is equal to or higher than 7.2 at php.

I'm not a developer, but I think that the benefits outweigh the disadvantages.

See https://en.wikipedia.org/wiki/Argon2

Unfortunately I do not speak English, therefore translated

Regards
DiamantTh

**Comment by My1** [comment]
well frankly argon2 has a quite a bit of added protection, especially due to being a memory hard function (or at least as memory hard as one wants) which makes it a lot more expensive to build crackers for it because in order to parallely crack those hashes you dont only need more processing power but more quickly accessible memory, on the other hand bcrypto and PBKDF2 arent really known to eat RAM, making things like ASIC attacks *relatively* cheap compared to argon2

on top of all that bcrypt has its limits with very long (iirc 72 or so characters is the limit) passwords, which might get annoying when a wordlist user tries to go really safe.

(by the way as I am a friend of DiamantTh I can also help with the communication)
