### ISSUE TITLE
inspircd testnet sent CAP DEL for something not advertised

### ISSUE THREAD

**Issue by jesopo** [inspircd/inspircd#1687]
Server send `CAP LS` response that didn't have `sasl` but then sent `CAP DEL` for `sasl` after registration burst. The connection was soon after the server had come back online so that might be something to do with it.

**Comment by SaberUK** [comment]
This is because when the IRC server started up the services server was not available so the cap was hidden even though it existed. When the server linked it sent the SASL mechlist which caused NotifyValueChange to be triggered and the capnotify module to send out a `DEL` and `NEW` for the cap value.

```
Sun Jul 28 2019 20:45:16 USEROUTPUT: C[890AAAAAA] O @time=2019-07-28T19:45:16.012Z :testnet.inspircd.org CAP BitBot DEL :sasl
Sun Jul 28 2019 20:45:16 USEROUTPUT: C[890AAAAAA] O @time=2019-07-28T19:45:16.012Z :testnet.inspircd.org CAP BitBot NEW :sasl=EXTERNAL,PLAIN
Sun Jul 28 2019 20:45:16 USERS: QuitUser: 890AAAAAA=BitBot 'The TLS connection was non-properly terminated.'
```
