### ISSUE TITLE
DNSBL module marking unreliable if connect class resolvehostnames enabled.

### ISSUE THREAD

**Issue by whoarethesevoices** [inspircd/inspircd#1770]
The DNSBL module fails to mark users reliably with connect classes that have resolvehostnames set to yes even though they are being successfully matched against a DNSBL...

Use case example:
Tor users, using exit nodes with an rDNS, being matched against DNSBL(s), initially receive a hostname as set via the DNSBL module... but reconnect where the marking fails, the exit node rDNS takes precedence...

Not sure if this is a timing or caching issue (or whatever...)... but this makes it very difficult to identify Tor users based on the hostname they should have received via the DNSBL module, especially if hostname cloaking is enabled.

Using: InspIRCd-3.5.0-*

**Comment by genius3000** [comment]
We seemed to narrow this down due to the following:
- m_dnsbl would have a cached result or just happen to get a result from the right DNSBL quick enough.
  - A vHost would be set here, through the `MARK` action.
- core_hostname_lookup would then finish and successfully get the user's hostname. This currently always resets the Displayed Host.
- m_cloaking would see that the Real Host and Displayed Host are a match, cloak would be applied as the Displayed Host.

Intended results would be for core_hostname_lookup to not override the Displayed Host and therefore m_cloaking wouldn't either; thus leaving the m_dnsbl vHost set as the Displayed Host.

I have a speculative fix that @whoarethesevoices is currently testing, with success so far, and will monitor for a bit for any oddities: https://github.com/inspircd/inspircd/compare/insp3...genius3000:insp3+hostname_resolution

**Comment by SadieCat** [comment]
@genius3000 LGTM, go ahead and merge it if you want.
