### ISSUE TITLE
Websocket + SSL issue

### ISSUE THREAD

**Issue by H7-25** [inspircd/inspircd#1779]
Using websocket module with ssl work fine, ssl connection can be etablished but sslinfo whois and check report it as a plain text connection, also is not possible join ssl only channels
1. configure websocket to listen on an ssl ports
2. configure a websocket client (kiwiirc for example) for a direct websocket connection using ssl
3. Run SSLINFO/WHOIS/CHECK or try to join an ssl only channel
4. Open i a browser wss://ircdhost.tld:7002 (or any ports configured for the websocket bind) to verify is ssl 

Running SSLINFO/WHOIS/CHECK on that user wil show it as a plain text connection
The user connected using wss can't join +z (sslonly) channels
Checking wss://ircdhost.tld:7002 will results valid ssl, and also checking the browser inspector of kiwiirc, used websocket will result wss.

Running InspIRCd-3.6.0-88602c694

**Comment by genius3000** [comment]
This is due to the function `IsSSL` only checking the first hook attached to a socket, in this case, `websocket` which is not an SSL type hook provider. I've pushed a speculative fix here: https://github.com/inspircd/inspircd/compare/insp3...genius3000:insp3+ssl_multi_hooks
@SadieCat feel free to clean it up some; I'm short on time for the next while.

**Comment by SadieCat** [comment]
@H7-25 This should be fixed in insp3 git now. Please can you check that it works?

**Comment by H7-25** [comment]
@SadieCat i can confirm it issue is fixed
