### ISSUE TITLE
SegmentCloak insecure?

### ISSUE THREAD

**Issue by rain-1** [inspircd/inspircd#1872]
It seems like the `SegmentCloak` function doesn't take in any secret data so it might be possible to reverse the cloaking by brute force (checking all IP addresses is feasible). It's possible I missed something, but I was curious if this was the case.

https://github.com/inspircd/inspircd/blob/6ff8f38a6d55970af1400cc78994e017ca351c39/src/modules/m_cloaking.cpp#L275

**Comment by Adam-** [comment]
It looks to me like it does take in secret data, and also includes it into the input to the hashing function:

```cpp
		std::string input;
		input.reserve(info.key.length() + 3 + item.length());
		input.append(1, id);
		input.append(info.key);
		input.append(1, '\0'); // null does not terminate a C++ string
		if (info.ignorecase)
			std::transform(item.begin(), item.end(), std::back_inserter(input), ::tolower);
		else
			input.append(item);
```

Since `info.key` is the `<cloak:key>` configuration value.

**Comment by SadieCat** [comment]
As Adam says `CloakInfo` contains the cloak key from the server configuration.

That said, all cloaking implementations are inherently vulnerable to brute forcing on some level because the range of potential values is very small. Given sufficient resources it is possible to brute force which is why v3 requires a 30+ character cloak key to make it sufficiently hard that it is not possible for all but the most dedicated attacker. If this low level of risk is not compatible with your threat model then you should use the [hostchange](https://docs.inspircd.org/3/modules/hostchange/) module which assigns a static hostname for users.

**Comment by rain-1** [comment]
Really appreciate the clear explanation, apologies for bringing up an invalid issue!
