### ISSUE TITLE
InspIRCd is not running. (Or PID File not found)

### ISSUE THREAD

**Issue by NightSommelier** [inspircd/inspircd#2061]
This problem has already been written about here #1621

I have the same bug on version InspIRCd-3.16.1

**Comment by SadieCat** [comment]
Are you sure its the same bug? That one has been fixed already. Just because it gives the same error message doesn't mean its the same bug.

How did you start InspIRCd? If you're using systemd or another init script that passes `--nopid` you will need to use that instead of our helper script.

If not can you please say how you installed InspIRCd and pastebin your `<pid>` configuration?

**Comment by SadieCat** [comment]
I can't reproduce this with the provided information. Please can you answer my questions so I can try to diagnose the issue?

**Comment by SadieCat** [comment]
I can't reproduce this and you haven't provided any more information as requested so I'm going to have to assume this is a user error.
