### ISSUE TITLE
/dccallow +nick doesn't work when nick has color code on vhost

### ISSUE THREAD

**Issue by tutipila** [inspircd/inspircd#2117]
/dccallow +nick doesn't work when nick is using vhost with color codes like pato!pato@71Olha.oOo.7PATO.QUACK!

Is there any workaround for this?

**Comment by SadieCat** [comment]
This module does not touch anything relating to your hostname. 

Please can you describe the exact command you are running and the behaviour that you are experiencing.

Please also provide your InspIRCd version.

**Comment by SadieCat** [comment]
I can't see anything in the module which would touch this so it sounds more like your client is breaking when it receives a DCC from a user with formatting characters in your host. Colour codes in hostnames are not common and have a habit of breaking clients in weird ways.

Its possible it could be a bug in v2 though which has since been fixed. v2 has been EOL for four years now.

**Comment by SadieCat** [comment]
I can't reproduce this in HexChat on v4. Please consider upgrading as v2 is extremely obsolete.
