### ISSUE TITLE
FD ReadError on user connect 

### ISSUE THREAD

**Issue by acaiafa** [inspircd/inspircd#307]
Hey,

I have a php script connecting a user to my inspircd server. in order for the user to successfully connect without errors I have to add a sleep(); into a portion of the fsock. Otherwise i continue to get a FD error. Below is a sample of the errors that appears and an strace during the failure. 

error: 
http://pastebin.ca/2206491

strace: 
http://pastebin.ca/2206497

**Comment by SaberUK** [comment]
Hi, it seems like this issue got buried! Sorry about that.

You are almost certainly using TLS on a plaintext port. Just because you have set `<bind:ssl>` does not mean that the listener is using TLS. The module you specified (either GnuTLS or OpenSSL) needs to be loaded and configured for the listener to support TLS.

If this is not the case and you're still having issues then please reply and i'll reopen the issue.
