### ISSUE TITLE
[2.0] m_override reports non-overrides

### ISSUE THREAD

**Issue by satmd** [inspircd/inspircd#425]
m_override will report a /mode #channel b regardless of permissions required.

The issue stems from m_override, line 108 being overly strict and not taking into account individual modes' levelrequired.

Suggestion: Before line 108, filter out modes that could have been done without override correctly.

**Comment by B00mX0r** [comment]
It appears to be for any listmode (+g, +e, etc). I noticed that you didn't specify this.

**Comment by SaberUK** [comment]
I'm having trouble replicating this against the current 2.0 git. Is it still an issue for you?

**Comment by genius3000** [comment]
I just updated my net to current 2.0 git a few days ago and still see this. Joining user's client requests ban list (allowed) but as override capable oper, it's shown as override.  
I believe this is what #1418 is for.

**Comment by Robby-** [comment]
I just ran into this issue as well. One network logged an override, while the other didn't. It turns out the difference was in the `<type:override>` setting. On one network its set as `<type:override="*">` and on the other its set as `<type:override="INVITE KEY LIMIT BANWALK">` The first one with `*` logs the override, while the latter one with the list of overrides does not log an override when doing a `/MODE #channel b`.
