### ISSUE TITLE
m_blockcaps: please add option to normalize sentence case rather than block all caps

### ISSUE THREAD

**Issue by kaniini** [inspircd/inspircd#628]
With the use of capslock as the best indicator we have on IRC of sarcasm, the default behaviour of +G is arguably antisocial.

Please make it normalize case instead, with the new behaviour as the default and the old as an opt-in.

**Comment by SaberUK** [comment]
Normalising case is not really possible without adding a dependency on something like libicu and even then it would be unreliable because of how different languages consider different letters to be upper and lower case.

The blockcaps module has also been deprecated in favour of another module which has more options for punishing caps users.
