### ISSUE TITLE
Proposal: WebSocket module for InspIRCd

### ISSUE THREAD

**Issue by barosl** [inspircd/inspircd#813]
I'm currently writing a WebSocket backend for InspIRCd. Here's the repo:

https://github.com/barosl/inspircd-m_websocket

Still experimental, and I have some issues:

1. Currently, it utilizes `<bind ssl="websocket">` to apply IO hook to ListenSocket. Looking at the upstream code, it seems that the only prefix that ListenSocket::ResetIOHookProvider() accept is `ssl/`. Am I correct? Is there a better way for this?
2. WebSocket is a message-based protocol, although the module sends a WebSocket frame with multiple IRC lines. Do you think it is a proper behavior? I mean, do we need to split a sending buffer (with multiple IRC lines) into corresponding multiple WebSocket frames? If the server doesn't do this, the client must split the content of a frame into lines. Con of this behavior would be low network performance, though I think its impact must be extremely low.

**Comment by sirwolfgang** [comment]
I just wanted to bump this and see if anyone has managed to use this for a web supporting a web client?

**Comment by Zayelion** [comment]
I stopped overall development for a client because I've been dealing with things in my project that are more critical like stablity because its in production and used by a small userbase that has a low attention span and is extremely critical.

 https://github.com/SalvationDevelopment/YGOPro-Support-System/blob/master/server/http/js/irc.js 

I found that the client has issues with closing properly due to the aforementioned needed code change. Also users connecting on the same IP get blocked if an websocket is open. There is enough functionality to develop a client but that is really it. I dont recommend this at scale till they put more attention to it, and for some reason this is being ignored. 

There is a mental disconnect to how useful browsers connecting to ircd's directly could be for I can only assume programmer-culture reasons, why would someone need to build a dumb down client when you have mIRC and other powerful IRC clients. Well basically every junior node.js project is building a mini IRCd or chat system. This functionality is obviously needed but its been back-burnnered and blocked by IRCd developers for a while now to the point everyone is dropping IRC in favor of custom solutions JUST for that browser access. This disconnect exist to the point someone built an IRCD in node and refuses to put in websocket support which is practically native at that point due to the nature of node.

Boggles my mind.

Looking around and shopping into other solutions they either involve Flash, which is dying and has its own issues with international support, or requires some additional server side solution with makes the security features of IRC not work properly, are cluncky, and a point of failure being a bottleneck. Even having a policy deamon randomly lockup is enough is enough for some people to drop IRC.

I feel this feature is criticial for making IRC more important in today's world over things such as 'gitter', gitter is not where devs talk, IRC is and historically always has been. Wont take someone more than 3 weeks to rewrite that whole services features after this is all functional, and it would be free with Inspircd at its core and yet another and very important feature over other IRCDs.

**Comment by SaberUK** [comment]
@Zayelion If you feel that this feature is so important that it is finished right now then I recommend finishing it yourself or paying @barosl to finish it. Unfortunately we aren't being paid to work on InspIRCd so other things have to take priority.

Also, there has been basically no things which could be considered "glitter" added to the development branch. Please don't make such statements when it is clear you have no clue what you are talking about.

**Comment by sirwolfgang** [comment]
@Zayelion I feel your pain. I am going through that debate with a team right now. Trying to put this together enough to show them how easy it is. There seems to be a sorta logic that revolves around it being more work to use an exsisting system then it is to roll your own. Which to me is mind boggling. You build better tires, not reinvent the wheel.

@SaberUK Reread that message, it wasn't an attack as you clearly took it. And he said gitter, as in gitter.im a chat service for github.

**Comment by Zayelion** [comment]
@SaberUK I cant be mad at the need for food, same for me and my project but I'll gladly pay for this feature. How much and what is @barosl 's paypal and I'll send it right over at the start of the month.

@sirwolfgang I had this debate with my previous team and it resulted in two massive forks in our projects repos. There is no glue between the wheels so its like cogs and gears with not teeth to transfer the momentum in the system, the gears are stripped or there is no axel/drive train sorta speak. For the moment your team members are correct which I hate to say. Even after the glue here is added for websockets other intergrations for single signon is going to be difficult.

**Comment by sirwolfgang** [comment]
@Zayelion I havn't gone too deep through the code, one of the frontend guys looked at it, and said it should be helpful. The SSO is one of the first things we figured out, and it is less of an issue. We are going to have a API layer that handles OAuth, storing the details in PG and generating a user session token. The user session token is then what is served for login. Its simlar to the way that Slack works.

**Comment by Zayelion** [comment]
> @Zayelion If you feel that this feature is so important that it is finished right now then I recommend finishing it yourself or paying @barosl to finish it. 

[Posted a bounty on it.](https://www.bountysource.com/issues/2916014-proposal-websocket-module-for-inspircd)

**Comment by Zayelion** [comment]
Increased Bounty by $100

**Comment by Zayelion** [comment]
Increased bounty to $220

**Comment by Polsaker** [comment]
Wow, that bounty and this is still waiting?

**Comment by alex-jch** [comment]
Will proper WebSockets support be implemented in the next release?

Charybdis has just added it (https://github.com/charybdis-ircd/charybdis/commit/b28cccb704ff711271eaa2a92564cef616fa862a) and UnrealIRCd has it planned.

**Comment by SaberUK** [comment]
@alex-jch Yes, but there are other important things which need to be done first, some of which affect the implementation of websocket support (i.e. we need to make it so a connection can have multiple `IOHook`s otherwise websocket support will have to go over plaintext which is non-ideal).

**Comment by briey** [comment]
Hello,
I have got a working websocket module for inspircd with websocketorigin filter.

**Comment by attilamolnar** [comment]
Sounds like the one I wrote a few years ago, is it this one: https://gist.github.com/attilamolnar/5000da620f5a838c5d4f34f47abba0a7 ?

**Comment by wgrimler** [comment]
Yes it is an old versions you wrote.
It works fine and stable with less than 300 users .
It  makes crash inspircd after less than 8 heures with more than 500 users.
I have tested also the revision 3 you made 2 days ago . And It also makes crash in the same conditions .
I use inspircd 2.0.21

**Comment by attilamolnar** [comment]
WIP branch for master: https://github.com/attilamolnar/inspircd/tree/master%2Bws

Config:

    <module name="sha1">
    <module name="websocket">
    <bind hook="websocket" port="7000">

Tested with GnuTLS and plaintext.

**Comment by attilamolnar** [comment]
This has been implemented.

**Comment by attilamolnar** [comment]
A few comments:

* Frames are sent as binary because the WebSocket protocol requires text frames to contain valid UTF-8 text but the standard IRC protocol has no such restriction (for example clients may send PRIVMSGs containing invalid UTF-8 or may join such channels, set such topics). Therefore it is not possible to send data as text frames unless all user input which is ever sent to clients is checked to be valid UTF-8. This is outside the scope of this module, but it may be changed in the future when all text input will be restricted to valid UTF-8.
* Frames don't have a semantic meaning. Quote from the RFC:

> Unless specified otherwise by an extension, frames have no semantic
   meaning.  An intermediary might coalesce and/or split frames, if no
   extensions were negotiated by the client and the server or if some
   extensions were negotiated, but the intermediary understood all the
   extensions negotiated and knows how to coalesce and/or split frames
   in the presence of these extensions.  One implication of this is that
   in absence of extensions, senders and receivers must not depend on
   the presence of specific frame boundaries.

There is no extension that gives a semantic meaning to frames, so according to the above, clients must not assume anything. Multiple IRC messages may be in one frame.
