### ISSUE TITLE
[discussion] wiki / online documentation

### ISSUE THREAD

**Issue by DjSlash** [inspircd/inspircd#831]
This topic has been coming up from time to time on IRC, but because of that the discussion is fragmented. 

A lot of people just want the old wiki to return. Personally, I don't think that's a good idea. Yes, it contains a lot of information, but it wasn't well-structured. Most of the information is outdated anyway. Main issue is documenting for different versions of InspIRCd. It has cost me a lot of time to try to update the documentation on the old wiki when 2.0 became stable. Most of the documentation was/is just a copy from the example configuration-/helpop-files. That's why I suggest that these files are going to be used to generate (static) html-files, so that every version has it's own place (similar as what readthedocs.org does). Then the wiki can be a place for extended information.

There are several people who think that contributing would be easier when there is no need to use git/PR's. I agree that contributing should be made a lot easier, but I like the idea of being able to create issues for the wiki. That said, once a decision is made, clear instructions should be provided on how one can contribute and what the conventions are.

**Comment by kiafaldorius** [comment]
Came here because the wiki was down. Trying to get setup information. Looks like it might be permanent this time since it's been down for over a week from what I can tell. Worrying since documentation is probably *the* most important public-facing aspect of an opensource project.

As far as I know, the general concensus on core documentation is to just leave the files in version control and update them as code is added/updated and features changed. As long as you keep them up to date with releases people can be confident that the doc files they read that come with the release is correct or close to it. man pages I believe work using this versioned-documentation-with-code idea

Github will render .md files with markdown so you get basic formatting. Github even has a built-in wiki if one of the Devs would be willing to enable it...

**Comment by SaberUK** [comment]
The wiki will be back up as soon as we get hold of Brain to

**Comment by kiafaldorius** [comment]
Once it's up, I'm willing to offer some help in porting the wiki over to the .md files in the docs directory and structure it somewhat. However, we need some sort of agreement with the devs and contributors to keep those files up to date...otherwise it'd be a lost cause...though syncing both the wiki and the docs in the repository might be a pain point, we should have a central source of "truth" for documentation and the repository seems like a good candidate.

Features don't fit docs or vice versa, then it's a bug.

**Comment by KeiroD** [comment]
I'd also be willing to offer hosting for the wiki as well. In fact, I'd also be willing to host a clone of the wiki in the event the main wiki goes down.

@kiafaldorius: I don't think keeping them in sync would be a major issue. I believe there're some tools available that help keep things in sync between wiki and the docs in the repo.

Maybe use one of the existing Documentation system to do that?
