### ISSUE TITLE
Install into User Program Files on Windows.

### ISSUE THREAD

**Issue by SadieCat** [inspircd/inspircd#951]
Installing into Program Files causes problems as since Vista it is only writable to by the admin user by default which results in permission errors when editing configuration files. The "correct" thing to do now is to install into the User Program Files directory.

This would mean we need to drop XP support but honestly at this point if you are using XP you deserve the pain of having to build from source yourself.

Reference: http://msdn.microsoft.com/en-us/library/windows/desktop/dd378457.aspx#FOLDERID_UserProgramFiles

**Comment by Link-Satonaka** [comment]
The "correct" thing to do is to have binaries in `Program Files` and configs in `%APPDATA%` (or install everything to `%APPDATA%`). Also acceptable is just having the installer make the folder `Program Files\inspircd\conf` User writable.

This scenario comes up often enough that I have long since configured a binding in vim to relaunch the current session as admin... and I'm not certain that protected config files is a bad thing.

**Comment by Sheogorath-SI** [comment]
For configs I would use `%appdata%\inspircd` but notice, that this folder is maybe synced and because inspircd is a server application `%programdata%\inspircd` would be the right place for configs. and maybe adding windows service (if it isn't already done) so `%programdata%\inspircd` would be the better place. 

I think the simplest way is add and option to setup to specify the config path. (maybe use registry)
