### ISSUE TITLE
xlinedb: Cannot move new to old database! File exists  (17)

### ISSUE THREAD

**Issue by MrGadget1024** [inspircd/inspircd#994]
Windows Server 2012 R2 with Stable Pre-built version of InspIRCd.

Spammed to log file every 5 seconds. Resolution...User the service is running under, in my case Network Service, needs at least modify rights to the data folder.

**Comment by SaberUK** [comment]
To clarify, the problem here is that we keep retrying every time OnBackgroundTimer runs. Instead, when we encounter an error we should not attempt to write the database for five minutes or so.

**Comment by ChrisLangsenkamp** [comment]
Not sure spamming every 5 minutes or 5 seconds matters much - it was days before I noticed it, and "File Exists" wasn't as obvious as "Access Denied" might have been, given that I hadn't needed to give any special rights to any of the folders up to this point. If there was mention of need to assign special rights in the conf files, I'm sorry I missed it.

**Comment by attilamolnar** [comment]
The messages are repeated because you have asked inspircd to save some data, and it fails to do so. You will lose your data unless the configuration mistake is corrected. In this case, it makes sense for it to complain very, very loudly. I'll change the 5 seconds to 30 or 60 in master.

> Not sure spamming every 5 minutes or 5 seconds matters much - it was days before I noticed it...

It's sent as a snomask and also logged, not sure how you missed it.

**Comment by ChrisLangsenkamp** [comment]
I'm always connected to the server as NetAdmin.

NetAdmin is using modes +Riors +CQcq

If you're saying I should have been getting spammed in my IRC client every 5 seconds...no, that didn't happen.

**Comment by ChrisLangsenkamp** [comment]
Update after reading and learning a bit:

I've done some investigative work to recreate the original issue and its origin.

The real issue stems from deliverables in the installer package.  Apparently xline.db is included in the package, and as a result the owner is set to "Administrators" along with every other file in the package. Log files are not included, therefore "Network Service" (NS) can create them with full control as "Creator Owner", but is locked out of xline.db because it exists and NS doesn't have explicit rights to the install location. Contributing to my not being aware of the problem stems from a combination of my being new at this, which I fully acknowledge, and the default modes setting in the NetAdmin type in opers.conf, which is "+s +CQcq" and that's not going give me the notices I should have been getting.

I changed the modes to "+Riors +ACGJKNOQXadfgjknotvx" and restored the original delivered xline.db and removed NS's priveledges to recreate the faulty scenerio, and sure enough, the error spamming began immediately.

Conclusion / Proposal:
I propose then to implement a change to the default deliverable opers.conf file giving the example types the broadest range of inclusion, along with a link reference to the wiki page that describes all the various modes, and perhaps not including an xline.db in the deliverable package unless absolutely necessary. If it's not included, NS can create it and modify / replace it without needing explicit rights to the existing file or folder.

**Comment by SadieCat** [comment]
As of v3 we shouldn't be shipping an xline.db file with the Windows installer and as of 68480cee67f3eb928dadca5ca776f38119e231e7 we now implement incremental backoff for xline database writes which should prevent opers being spammed when a database write fails.
